config/routes.rb
Rails.application.routes.draw do
  get 'welcome/info',  as: 'info'
  get 'welcome/help',  as: 'help'
  get 'welcome/about', as: 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#info'
  devise_for :users
  resources :users, only: [:show]
  resources :offsprings do
    resources :assignments, except: [:index, :show]
  end
  resources :rooms, only: [:index]
  resources :shifts, only: [:show]

  namespace :admin do
    resources :users, only: [:index]
    resources :offsprings, only: [:index]
    resources :rooms, only: [:index]
    resources :shifts, only: [:show]
  end
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  i18n_scope = 'activerecord.errors.models.assignment.attributes'.freeze
  belongs_to :offspring
  belongs_to :shift
  validates :offspring, presence: true, uniqueness: true
  validates :shift,     presence: true

  validates_each :shift do |assignment|
    assignment.errors.add(:shift, I18n.t('shift.no_sites_available', scope: i18n_scope)) unless assignment.shift&.sites_available?
  end

  def full_name
    @full_name ||= shift.full_name
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def new
    unless(@offspring = Offspring.includes(:user).find_by(id: params[:offspring_id], user_id: current_user.id))
      flash[:alert] = t '.offspring_not_found'
      redirect_to offsprings_path
    end
    @rooms = Room.all.includes(:shifts)
    @shifts = Shift.all
  end

  def create
    Assignment.transaction do
      @assignment = Assignment.find_by(offspring: params[:offspring_id]) || Assignment.new
      @assignment.shift = Shift.find_by(id: params[:shift_id])
      @assignment.offspring = Offspring.find_by(id: params[:offspring_id], user: current_user)

      if @assignment.offspring.nil?
        flash[:alert] = (t '.assignment_not_added')
        redirect_to offsprings_path
      elsif @assignment.save
        AssignmentsMailer.shift_assigned_email(current_user, @assignment.offspring, @assignment).deliver_later
        flash[:success] = (t '.assignment_added')
        redirect_to offsprings_path
      else
        flash[:alert] = (t '.assignment_not_added')
        render 'new'
      end
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_room.html.erb
<div class="col-xs-12">
  <div class="panel panel-success">
    <div class="panel-heading">
      <div class="panel-title">
        <h3>
        <strong>
          <%= room.name %>
          (
          <%= t '.capacity' %>:
          <%= room.capacity %>
          )
        </strong>
        </h3>
      </div>
    </div>
    <div class="container-fluid">
      <nav class="row">
        <% Shift.day_of_weeks.keys[0..4].each do |wd| %>
            <% unless room.shifts.send(wd).empty? %>
                <div class="alert alert-success"> <h4><strong><%= t wd, scope: "week" %></strong></h4></div>
                <br>
                <ul class="nav nav-tabs">
                  <%= render partial: 'shift', collection: room.shifts.send(wd) %>
                </ul>
            <% end %>
        <% end %>
      </nav>
    </div>
  </div>
</div>

app/views/assignments/_shift.html.erb
<li>
  <div class = "panel panel-info">
    <div class="panel-heading">
      <strong><%= shift.start_time %> => <%= shift.end_time %> </strong>
    </div>
    <div class="panel-body">
      <% if shift.sites_available? %>
        <%= link_to t(".select"), offspring_assignments_path(offspring_id: @offspring, shift_id: shift.id), method: :post,
                    class: "btn btn-primary" %>
      <% else %>
          <strong><%= t '.is_full' %></strong>
      <% end %>
        <p> <%= "#{t '.sites_available'}" %> <span class='badge'>  <%= shift.sites_available %>  </span></p>
    </div>
  </div>
</li>

app/views/assignments/new.html.erb
<div class="container-fluid">
  <h2> <%=t('.choose_shifts', who: @offspring.first_name)%></h2>

  <% unless @rooms.empty? %>
      <%= render partial: 'room', collection: @rooms %>
  <% end %>
</div>