config/routes.rb
Rails.application.routes.draw do
  get 'welcome/info',  as: 'info'
  get 'welcome/help',  as: 'help'
  get 'welcome/about', as: 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#info'
  devise_for :users
  resources :users, only: [:show]
  resources :offsprings do
    resources :assignments, except: [:index, :show]
  end
  resources :rooms, only: [:index]
  resources :shifts, only: [:show]

  namespace :admin do
    resources :users, only: [:index]
    resources :offsprings, only: [:index]
    resources :rooms, only: [:index]
    resources :shifts, only: [:show]
  end
end

app/models/offspring.rb
class Offspring < ApplicationRecord
  require 'csv'
  i18n_scope = 'activerecord.errors.models.offspring.attributes'.freeze
  belongs_to :user
  has_one :assignment, dependent: :destroy
  has_one :shift, through: :assignment
  enum grade: { primary_first: 1, primary_second: 2, primary_third: 3, others: 0 }
  validates :first_name, presence: true, length: { within: 2..60 }
  validates :last_name,  presence: true, length: { within: 2..60 }
  validates :grade, presence: true
  # Validates surname is the same for all offspring

  validates_each :last_name do |offspring|
    if offspring.user && offspring.user.offsprings.first
      unless offspring.last_name == offspring.user.offsprings.first.last_name
        offspring.errors.add(:last_name, I18n.t('last_name.different', scope: i18n_scope))
      end
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.to_csv
    attributes = %w[id first_name last_name grade shift&.full_name user&.full_name]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |offspring|
        csv << attributes.map{ |attr| offspring.instance_eval(attr) }
      end
    end
  end
end

app/controllers/admin/offsprings_controller.rb
class Admin::OffspringsController < AdminController
  def index
    @offsprings = Offspring.all

    respond_to do |format|
      format.html
      format.csv { send_data @offsprings.to_csv, filename: "offsprings-#{Date.today}.csv" }
    end
  end
end

app/controllers/offsprings_controller.rb
class OffspringsController < ApplicationController
  ALLOWED_GRADES = ['primary_first'].freeze

  def new
    @offspring = Offspring.new(user: current_user)
  end

  def index
    @offsprings = Offspring.includes(:assignment).where(user: current_user)
  end

  def create
    unless ALLOWED_GRADES.include? offsprings_params[:grade]
      flash[:danger] = t '.invalid_grade'
      redirect_to offsprings_path
      return
    end
    @offspring = Offspring.new(offsprings_params)
    @offspring.user = current_user
    if @offspring.save
      flash[:success] = t('.offspring_added', offspring: @offspring.first_name)
      redirect_to user_path(current_user)
    else
      flash[:alert] = t '.offspring_not_added'
      render :new
    end
  end

  def edit
    @offspring = Offspring.find_by(id: params[:id], user: current_user)
    if @offspring.nil?
      flash[:alert] = t '.offspring_not_found'
      redirect_to offsprings_path
    end
  end

  def show
    if current_user.admin?
      @offspring = Offspring.find_by(id: params[:id])
    else
      @offspring = Offspring.find_by(user: current_user, id: params[:id])
    end

    @assignment = Assignment.find_by(offspring: @offspring)
    if @offspring.nil?
      flash[:alert] = t('.offspring_not_found')
      redirect_to user_path(current_user)
    end
  end

  def update
    @offspring = Offspring.find_by(id: params[:id], user: current_user)
    if @offspring.nil?
      flash[:alert] = t '.offspring_not_found'
      redirect_to offsprings_path
    elsif @offspring.update_attributes(offsprings_params)
      flash[:success] = t('.offspring_updated', name: @offspring.full_name)
      redirect_to offspring_path(@offspring)
    else
      flash[:alert] = t '.offspring_not_updated'
      render :edit
    end
  end

  def destroy
    @offspring = Offspring.find_by(id: params["id"], user: current_user)
    if @offspring.nil?
      flash[:alert] = t '.offspring_not_found'
    elsif @offspring.destroy
      flash[:success] = (t ".offspring_deleted", offspring: @offspring.first_name)
    else
      flash[:alert] = (t ".offspring_not_deleted")
    end
    redirect_to offsprings_path
  end

  private

  def offsprings_params
    params.require(:offspring).permit(:first_name, :last_name, :grade)
  end
end

app/helpers/admin/offsprings_helper.rb
module Admin::OffspringsHelper
end

app/helpers/offsprings_helper.rb
module OffspringsHelper
end

app/views/offsprings/_offspring.html.erb
<div class="list-group-item">
  <div class="list-view-pf-actions">
    <%= link_to t('.show'), offspring_path(offspring), class: "btn btn-primary" %>
    <%= link_to t('.assign'), new_offspring_assignment_path(offspring), class: "btn btn-warning" %>
  </div>

  <div class="list-view-pf-main-info">
    <div class="list-view-pf-left">
      <span class="fa fa-user list-view-pf-icon-sm"></span>
    </div>
    <div class="list-view-pf-body">
      <div class="list-view-pf-description">
        <div class="list-group-item-heading">
          <%= link_to offspring.first_name, offspring_path(offspring) %>
          <b>
            <%= offspring.last_name %>
          </b>
        </div>
        <div class="list-group-item-text">
          <% if offspring.assignment.nil? %>
              <%= t '.no_assignment_yet' %>
          <% else %>
              <strong class="btn btn-warning"><%= offspring.assignment.full_name %></strong>
          <% end %>
        </div>
      </div>
      <div class="list-view-pf-additional-info">
        <div class="list-view-pf-additional-info-item">
          <%= t "grades.#{offspring.grade}" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offsprings/edit.html.erb
<div class="container-fluid">
<h2>
  <%= t '.edit_offspring', name: @offspring.full_name %>
</h2>
<%= form_for(@offspring, url: {action: "update"}) do |f| %>
    <form class="form-horizontal">
      <%= render 'layouts/form_errors', object: @offspring %>
      <div class="form-group">
        <div class="control-label">
          <%= f.label :first_name %>
        </div>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <div class="control-label">
          <%= f.label :last_name %>
        </div>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <div class="control-label">
          <%= f.label :grade %>
        </div>
        <%= f.select :grade, Offspring.grades.map { |w, _y| [I18n.t(w, scope: 'grades'), w] }, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit (t'.update'), class: "btn btn-primary btn-lg" %>
      </div>
    </form>
<% end %>
</div>

app/views/offsprings/index.html.erb
<div class="container-fluid">
  <h2> <%=t('.offsprings')%></h2>

  <div class="list-group list-view-pf list-view-pf-view">
      <%= render @offsprings || t('.no_offsprings_yet') %>
  </div>

  <div class="btn-group">
    <%= link_to t('.add_offspring'), new_offspring_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/offsprings/new.html.erb
<div class="container-fluid">
  <h2>
    <%= t '.new_offspring' %>
  </h2>
  <%= form_for(@offspring, url: {action: "create"}) do |f| %>
      <form class="form-horizontal">
        <%= render 'layouts/form_errors', object: @offspring %>
        <div class="form-group">
          <div class="control-label">
            <%= f.label :first_name %>
          </div>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <div class="control-label">
            <%= f.label :last_name %>
          </div>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <div class="control-label">
            <%= f.label :grade %>
          </div>
          <%= f.select :grade, Offspring.grades.map { |w, _y| [I18n.t(w, scope: 'grades'), w] }, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit (t'.create'), class: "btn btn-primary btn-lg" %>
        </div>
      </form>
  <% end %>
</div>

app/views/offsprings/show.html.erb
<div class="container-fluid">
  <h2>
    <%= t '.offspring' %>
  </h2>
  <div class="form">
    <div class="form-group">
      <div class="control-label text_tag">
        <%= Offspring.human_attribute_name 'first_name' %>
      </div>
      <div class="form-control" disabled="disabled">
        <%= @offspring.first_name %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label">
        <%= Offspring.human_attribute_name 'last_name' %>
      </div>
      <div class="form-control" disabled="disabled">
        <%= @offspring.last_name %>
      </div>
    </div>
      <div class="form-group">
        <div class="control-label">
          <%= Offspring.human_attribute_name :grade %>
        </div>
        <div class="form-control" disabled="disabled">
          <%= t "grades.#{@offspring.grade}" %>
        </div>
      </div>
    </form>
  </div>
</div>

<p>
  <% if @assignment %>
    <div class="alert alert-success"> <h4><strong><%= @assignment.full_name %></strong></h4> <%= link_to t('.assign'), new_offspring_assignment_path(@offspring), class: "btn btn-warning" %></div>
  <% else %>
    <div class="alert alert-default"> <h4><strong><%= t '.no_assignment_yet' %></strong></h4> <%= link_to t('.assign'), new_offspring_assignment_path(@offspring), class: "btn btn-warning" %></div>
  <% end %>


</p>
<br>
<%= link_to t('.back'), :back, class: "btn btn-default"%>
<%= link_to t('.edit'), edit_offspring_path(@offspring), class: "btn btn-primary"%>

<%= link_to (t'.delete_offspring'), offspring_path(@offspring), class: "btn btn-danger",
data: { confirm: (t'.are_you_sure?') }, method: :delete %>