config/routes.rb
Rails.application.routes.draw do
  get 'welcome/info',  as: 'info'
  get 'welcome/help',  as: 'help'
  get 'welcome/about', as: 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#info'
  devise_for :users
  resources :users, only: [:show]
  resources :offsprings do
    resources :assignments, except: [:index, :show]
  end
  resources :rooms, only: [:index]
  resources :shifts, only: [:show]

  namespace :admin do
    resources :users, only: [:index]
    resources :offsprings, only: [:index]
    resources :rooms, only: [:index]
    resources :shifts, only: [:show]
  end
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :room
  TIME_REGEX = /\A([01]\d|2[0123]):[012345]\d\z/

  has_many :assignments, dependent: :destroy
  enum :day_of_week => Date::DAYS_INTO_WEEK
  validates :day_of_week, presence: true
  validates :start_time, presence: true
  validates :start_time, format: { with: TIME_REGEX, message: I18n.t(".start_time.invalid_format") }
  validates :end_time, presence: true
  validates :end_time, format: { with: TIME_REGEX, message: I18n.t(".start_time.invalid_format") }

  validates_each :end_time do |shift|
    shift.errors.add(:shift, I18n.t(".end_time.end_time_earlier_than_start_time")) if
        shift.start_time > shift.end_time
  end

  validates :sites_reserved, numericality: { only_integer: true }

  def shift_start
    "#{I18n.t day_of_week, scope: 'week'} #{start_time}"
  end

  def room_name
    @room_name || room.name
  end

  def full_name
    "#{room_name}: #{shift_start}"
  end

  def capacity
    @capacity || room.capacity
  end

  def sites_available
    capacity - Assignment.where(shift: self).count - sites_reserved
  end

  def sites_available?
    sites_available > 0
  end
end

app/controllers/admin/shifts_controller.rb
class Admin::ShiftsController < AdminController

  def show
    @shift = Shift.find_by(id: params[:id])
    @offsprings = Offspring.includes(:assignment).where('assignments.shift_id': @shift)

    if @shift.nil?
      flash[:alert] = t('.shift_not_found')
      redirect_to admin_rooms_path
    end


    respond_to do |format|
      format.html
      format.csv { send_data @offsprings.to_csv, filename: "shift-#{@shift.full_name}-#{Date.today}.csv" }
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def show
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/admin/shifts/_offspring.html.erb
<tr>
  <td>
    <%= link_to offspring.id, offspring_path(offspring) %>
  </td>
  <td>
    <%= link_to offspring.first_name, offspring_path(offspring) %>
  </td>
  <td>
    <%= link_to offspring.last_name, offspring_path(offspring) %>
  </td>
  <td>
    <%= I18n.t offspring.grade, scope: 'grades' %>
  </td>

  <td>
    <%= offspring.shift&.full_name %>
  </td>

  <td>
    <%= link_to offspring.user.full_name, user_path(offspring.user) %>

  </td>

  <td>
    <%= l offspring.created_at %>
  </td>

  <td>
    <%= l offspring.updated_at %>
  </td>
</tr>

app/views/admin/shifts/show.html.erb
<h1><strong><%= @shift.full_name %></strong></h1>

<div class="container-fluid">
  <h2> <%=t('.offsprings')%></h2>
  <p>
    <%= link_to(t('.download_offsprings'), admin_shift_path(@shift, format: :csv), class: "btn btn-lg btn-primary") %>
  </p>

  <table class="datatable table table-striped table-bordered">
    <thead>
    <tr>
      <th>
        <%= Offspring.human_attribute_name('id') %>
      </th>
      <th>
        <%= Offspring.human_attribute_name('first_name') %>
      </th>
      <th>
        <%= Offspring.human_attribute_name('last_name') %>
      </th>
      <th>
        <%= Offspring.human_attribute_name('grade') %>
      </th>
      <th>
        <%= Offspring.human_attribute_name('shift') %>
      </th>
      <th>
        <%= Offspring.human_attribute_name('user') %>
      </th>
      <th>
        <%= Offspring.human_attribute_name('created_at') %>
      </th>
      <th>
        <%= Offspring.human_attribute_name('updated_at') %>
      </th>
    </tr>
    </thead>
    <tbody>
    <%= render @offsprings %>
    </tbody>
  </table>
</div>

<script>
    // Initialize Datatables
    $(document).ready(function() {
        $('.datatable').dataTable();
    });
</script>