config/routes.rb
Rails.application.routes.draw do
  get 'welcome/info',  as: 'info'
  get 'welcome/help',  as: 'help'
  get 'welcome/about', as: 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#info'
  devise_for :users
  resources :users, only: [:show]
  resources :offsprings do
    resources :assignments, except: [:index, :show]
  end
  resources :rooms, only: [:index]
  resources :shifts, only: [:show]

  namespace :admin do
    resources :users, only: [:index]
    resources :offsprings, only: [:index]
    resources :rooms, only: [:index]
    resources :shifts, only: [:show]
  end
end

app/views/layouts/_admin_masthead.html.erb
<nav class="navbar navbar-default navbar-pf" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target=".navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <%= image_tag("brand.jpg", height: "64", alt: (t 'application.name').to_s) %>
    </a>
  </div>
  <div class="collapse navbar-collapse navbar-collapse-1">
    <ul class="nav navbar-nav navbar-utility">
      <li>
        <a href="#">
          <%= user_signed_in? ? t(".signed_in"): t(".not_signed_in") %>
        </a>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span class="pficon pficon-user"></span>
          <%= user_signed_in? ? current_user.first_name : t(".not_identified") %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to  new_user_session_path do %>
                <div class="fa fa-sign-in">
                  <%= (t '.log_in') %>
                </div>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
                <div class="fa fa-sign-out">
                  <%= (t '.log_out')  %>
                </div>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to new_user_registration_path do %>
                <div class="fa fa-user-plus">
                  <%= (t '.sign_up') %>
                </div>
            <% end %>
          </li>

          <li class="divider"></li>
          <li>
            <%= link_to about_path do %>
                <div class="fa fa-question-circle-o">
                  <%= (t '.about')  %>
                </div>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-primary">
      <li>
        <%= link_to (t'.users'), admin_users_path %>
      </li>
      <li>
        <%= link_to t('.offsprings'), admin_offsprings_path %>
      </li>
      <li>
        <% if user_signed_in? %>
            <%= link_to t('.rooms'), admin_rooms_path %>
        <% end %>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= (t ".help") %>
          <b class="caret"></b>
          <ul class="dropdown-menu">
            <li>
              <%= link_to (t '.help'), help_path %>
              <%= link_to (t '.info'), info_path %>
              <%= link_to (t '.about'), about_path %>
            </li>
          </ul>
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_alerts.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert <%= alert_class(message_type) %> fade in">
      <button area-hidden="true" class="close" data-dismiss="alert" type="button">
        <span class="pficon pficon-close"></span>
      </button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <ul class="list-group">
      <% object.errors.full_messages.each do |msg| %>
      <li class="list-group item">
          <div class="alert alert-danger">
            <span>
              <div class="pficon pficon-error-circle-o"></div>
              <strong>
                <%= msg %>
              </strong>
            </span>
          </div>
      </li>
      <% end %>
  </ul>
<% end %>

app/views/layouts/_masthead.html.erb
<nav class="navbar navbar-default navbar-pf" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target=".navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <%= image_tag("brand.jpg", height: "64", alt: (t 'application.name').to_s) %>
    </a>
  </div>
  <div class="collapse navbar-collapse navbar-collapse-1">
    <ul class="nav navbar-nav navbar-utility">
      <li>
        <a href="#">
          <%= user_signed_in? ? t(".signed_in"): t(".not_signed_in") %>
        </a>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span class="pficon pficon-user"></span>
          <%= user_signed_in? ? current_user.first_name : t(".not_identified") %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to  new_user_session_path do %>
                <div class="fa fa-sign-in">
                  <%= (t '.log_in') %>
                </div>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
                <div class="fa fa-sign-out">
                  <%= (t '.log_out')  %>
                </div>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to new_user_registration_path do %>
                <div class="fa fa-user-plus">
                  <%= (t '.sign_up') %>
                </div>
            <% end %>
          </li>

          <li class="divider"></li>
          <li>
            <%= link_to about_path do %>
                <div class="fa fa-question-circle-o">
                  <%= (t '.about')  %>
                </div>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-primary">
      <li>
        <% if user_signed_in? %>
            <%= link_to (t'.user_panel'), user_path(current_user) %>
        <% else %>
            <%= link_to (t'.log_in'), new_user_session_path %>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
            <%= link_to t('.offsprings'), offsprings_path %>
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>
            <%= link_to t('.rooms'), rooms_path %>
        <% end %>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= (t ".help") %>
          <b class="caret"></b>
          <ul class="dropdown-menu">
            <li>
              <%= link_to (t '.help'), help_path %>
              <%= link_to (t '.info'), info_path %>
              <%= link_to (t '.about'), about_path %>
            </li>
          </ul>
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <title><%= t 'application.name' %></title>

  </head>

  <body>
    <% if current_user&.admin? %>
      <%= render 'layouts/admin_masthead' %>
    <% else %>
      <%= render '/layouts/masthead' %>
    <% end %>
    <%= render '/layouts/alerts' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>